### ISSUE TITLE
Conference bookmarks broken in Inverse client

### ISSUE THREAD

**Issue by deleolajide** [igniterealtime/Pade#14]
inverse.min.js:48049 FATAL: TypeError: Cannot read property 'save' of undefined
    at Element.<anonymous> (chrome-extension://fohfnhgabmicpkjcpjpjongpijcffaba/inverse/plugins/pade.js:148:34)
    at Function.each (chrome-extension://fohfnhgabmicpkjcpjpjongpijcffaba/inverse/jquery/dist/jquery.min.js:4:5347)
    at init.each (chrome-extension://fohfnhgabmicpkjcpjpjongpijcffaba/inverse/jquery/dist/jquery.min.js:4:1999)
    at chrome-extension://fohfnhgabmicpkjcpjpjongpijcffaba/inverse/plugins/pade.js:136:50
    at Strophe.Handler.handler (chrome-extension://fohfnhgabmicpkjcpjpjongpijcffaba/inverse/inverse/dist/inverse.min.js:41764:25)
    at Strophe.Handler.run (chrome-extension://fohfnhgabmicpkjcpjpjongpijcffaba/inverse/inverse/dist/inverse.min.js:40937:27)
    at chrome-extension://fohfnhgabmicpkjcpjpjongpijcffaba/inverse/inverse/dist/inverse.min.js:42197:34
    at Object.forEachChild (chrome-extension://fohfnhgabmicpkjcpjpjongpijcffaba/inverse/inverse/dist/inverse.min.js:39905:17)
    at Strophe.Connection._dataRecv (chrome-extension://fohfnhgabmicpkjcpjpjongpijcffaba/inverse/inverse/dist/inverse.min.js:42185:17)
    at Strophe.Websocket._onMessage (chrome-extension://fohfnhgabmicpkjcpjpjongpijcffaba/inverse/inverse/dist/inverse.min.js:44671:20)

**Comment by deleolajide** [comment]
fixed in 0.3.6
