### ISSUE TITLE
Pade doesnt connect anymore

### ISSUE THREAD

**Issue by JericoPablo** [igniterealtime/pade#246]
Hi,

the browser extension client Pade doesnt connect anymore. The errors started after i updated all the Pade Plugins on Openfire. Pade Focus Component, Pade VideoBridge Plugin, Pade Server. On the server side when i open the logs with Openfire Admin-Consol i can see these errors:

at org.jitsi.videobridge.RtpChannel.initialize(RtpChannel.java:907) ~[jitsi-videobridge-1.1-20200124.173127-125.jar:?]
at org.jitsi.videobridge.Content.createRtpChannel(Content.java:340) ~[jitsi-videobridge-1.1-20200124.173127-125.jar:?]
at org.jitsi.videobridge.Content.createRtpChannel(Content.java:264) ~[jitsi-videobridge-1.1-20200124.173127-125.jar:?]
at org.jitsi.videobridge.health.Health.check(Health.java:152) ~[jitsi-videobridge-1.1-20200124.173127-125.jar:?]
at org.jitsi.videobridge.health.Health.doCheck(Health.java:244) ~[jitsi-videobridge-1.1-20200124.173127-125.jar:?]
at org.jitsi.videobridge.health.Health.doRun(Health.java:495) [jitsi-videobridge-1.1-20200124.173127-125.jar:?]
at org.jitsi.utils.concurrent.PeriodicRunnableWithObject.run(PeriodicRunnableWithObject.java:87) [jitsi-utils-1.0-14-ge5cb3c9.jar:?]
at org.jitsi.utils.concurrent.RecurringRunnableExecutor.run(RecurringRunnableExecutor.java:216) [jitsi-utils-1.0-14-ge5cb3c9.jar:?]
at org.jitsi.utils.concurrent.RecurringRunnableExecutor.runInThread(RecurringRunnableExecutor.java:292) [jitsi-utils-1.0-14-ge5cb3c9.jar:?]
at org.jitsi.utils.concurrent.RecurringRunnableExecutor.access$000(RecurringRunnableExecutor.java:36) [jitsi-utils-1.0-14-ge5cb3c9.jar:?]
at org.jitsi.utils.concurrent.RecurringRunnableExecutor$1.run(RecurringRunnableExecutor.java:328) [jitsi-utils-1.0-14-ge5cb3c9.jar:?]
2020.11.10 09:22:59 org.jitsi.videobridge.health.Health - Health check failed in 22ms:
java.lang.NullPointerException: null

it keeps logging this error every 10 sec. can anyone help me out?

EDIT:

also i found something i did not see between all the spamed errors:

**_2020.11.10 08:46:23 com.reucon.openfire.plugin.archive.impl.JdbcPersistenceManager - Error selecting conversation
org.postgresql.util.PSQLException: Der Spaltenname stanza wurde in diesem ResultSet nicht gefunden._**

at org.postgresql.jdbc.PgResultSet.findColumn(PgResultSet.java:2614) ~[postgresql-42.2.14.jar:42.2.14]
at org.postgresql.jdbc.PgResultSet.getString(PgResultSet.java:2487) ~[postgresql-42.2.14.jar:42.2.14]
at org.apache.commons.dbcp2.DelegatingResultSet.getString(DelegatingResultSet.java:898) ~[commons-dbcp2-2.6.0.jar:2.6.0]
at org.apache.commons.dbcp2.DelegatingResultSet.getString(DelegatingResultSet.java:898) ~[commons-dbcp2-2.6.0.jar:2.6.0]
at com.reucon.openfire.plugin.archive.impl.JdbcPersistenceManager.extractMessage(JdbcPersistenceManager.java:984) ~[monitoring-2.0.1.jar:?]
at com.reucon.openfire.plugin.archive.impl.JdbcPersistenceManager.getConversation(JdbcPersistenceManager.java:886) [monitoring-2.0.1.jar:?]
at com.reucon.openfire.plugin.archive.impl.JdbcPersistenceManager.getConversation(JdbcPersistenceManager.java:801) [monitoring-2.0.1.jar:?]
at com.reucon.openfire.plugin.archive.xep0136.IQRetrieveHandler.retrieve(IQRetrieveHandler.java:107) [monitoring-2.0.1.jar:?]
at com.reucon.openfire.plugin.archive.xep0136.IQRetrieveHandler.handleIQ(IQRetrieveHandler.java:39) [monitoring-2.0.1.jar:?]
at com.reucon.openfire.plugin.archive.xep.AbstractXepSupport$1.handleIQ(AbstractXepSupport.java:42) [monitoring-2.0.1.jar:?]
at org.jivesoftware.openfire.handler.IQHandler.process(IQHandler.java:62) [xmppserver-4.7.0-SNAPSHOT.jar:4.7.0-SNAPSHOT]
at org.jivesoftware.openfire.IQRouter.handle(IQRouter.java:399) [xmppserver-4.7.0-SNAPSHOT.jar:4.7.0-SNAPSHOT]
at org.jivesoftware.openfire.IQRouter.route(IQRouter.java:118) [xmppserver-4.7.0-SNAPSHOT.jar:4.7.0-SNAPSHOT]
at org.jivesoftware.openfire.spi.PacketRouterImpl.route(PacketRouterImpl.java:74) [xmppserver-4.7.0-SNAPSHOT.jar:4.7.0-SNAPSHOT]
at org.jivesoftware.openfire.net.StanzaHandler.processIQ(StanzaHandler.java:380) [xmppserver-4.7.0-SNAPSHOT.jar:4.7.0-SNAPSHOT]
at org.jivesoftware.openfire.net.ClientStanzaHandler.processIQ(ClientStanzaHandler.java:95) [xmppserver-4.7.0-SNAPSHOT.jar:4.7.0-SNAPSHOT]
at org.jivesoftware.openfire.net.StanzaHandler.process(StanzaHandler.java:322) [xmppserver-4.7.0-SNAPSHOT.jar:4.7.0-SNAPSHOT]
at org.jivesoftware.openfire.net.StanzaHandler.process(StanzaHandler.java:209) [xmppserver-4.7.0-SNAPSHOT.jar:4.7.0-SNAPSHOT]
at org.jivesoftware.openfire.nio.ConnectionHandler.messageReceived(ConnectionHandler.java:183) [xmppserver-4.7.0-SNAPSHOT.jar:4.7.0-SNAPSHOT]
at org.apache.mina.core.filterchain.DefaultIoFilterChain$TailFilter.messageReceived(DefaultIoFilterChain.java:1015) [mina-core-2.1.3.jar:?]
at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:650) [mina-core-2.1.3.jar:?]
at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1300(DefaultIoFilterChain.java:49) [mina-core-2.1.3.jar:?]
at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.messageReceived(DefaultIoFilterChain.java:1128) [mina-core-2.1.3.jar:?]
at org.apache.mina.core.filterchain.IoFilterAdapter.messageReceived(IoFilterAdapter.java:122) [mina-core-2.1.3.jar:?]
at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:650) [mina-core-2.1.3.jar:?]
at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1300(DefaultIoFilterChain.java:49) [mina-core-2.1.3.jar:?]
at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.messageReceived(DefaultIoFilterChain.java:1128) [mina-core-2.1.3.jar:?]
at org.apache.mina.filter.codec.ProtocolCodecFilter$ProtocolDecoderOutputImpl.flush(ProtocolCodecFilter.java:413) [mina-core-2.1.3.jar:?]
at org.apache.mina.filter.codec.ProtocolCodecFilter.messageReceived(ProtocolCodecFilter.java:257) [mina-core-2.1.3.jar:?]
at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:650) [mina-core-2.1.3.jar:?]
at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1300(DefaultIoFilterChain.java:49) [mina-core-2.1.3.jar:?]
at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.messageReceived(DefaultIoFilterChain.java:1128) [mina-core-2.1.3.jar:?]
at org.apache.mina.filter.compression.CompressionFilter.messageReceived(CompressionFilter.java:169) [mina-filter-compression-2.1.3.jar:?]
at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:650) [mina-core-2.1.3.jar:?]
at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1300(DefaultIoFilterChain.java:49) [mina-core-2.1.3.jar:?]
at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.messageReceived(DefaultIoFilterChain.java:1128) [mina-core-2.1.3.jar:?]
at org.apache.mina.core.filterchain.IoFilterEvent.fire(IoFilterEvent.java:106) [mina-core-2.1.3.jar:?]
at org.apache.mina.core.session.IoEvent.run(IoEvent.java:89) [mina-core-2.1.3.jar:?]
at org.apache.mina.filter.executor.OrderedThreadPoolExecutor$Worker.runTask(OrderedThreadPoolExecutor.java:766) [mina-core-2.1.3.jar:?]
at org.apache.mina.filter.executor.OrderedThreadPoolExecutor$Worker.runTasks(OrderedThreadPoolExecutor.java:758) [mina-core-2.1.3.jar:?]
at org.apache.mina.filter.executor.OrderedThreadPoolExecutor$Worker.run(OrderedThreadPoolExecutor.java:697) [mina-core-2.1.3.jar:?]
at java.lang.Thread.run(Thread.java:834) [?:?]

 Error selecting conversation
org.postgresql.util.PSQLException: Der Spaltenname stanza wurde in diesem ResultSet nicht gefunden.

it couldnt find the column "stanza"?

**Comment by deleolajide** [comment]
The health check failed error might be cured with a  restart of the  hardware server running Openfire. If that fails then I suggest you go back to [version 1.0.1](https://github.com/igniterealtime/openfire-pade-plugin/releases/tag/v1.0.1)
