### ISSUE TITLE
Pade floods the server with VCard set requests

### ISSUE THREAD

**Issue by guusdk** [igniterealtime/Pade#40]
Pade appears to indefinitely try to set a VCard. On servers were VCards cannot be modified, this is causing problems. Pade shouldn't continuously retry failed requests.

The error below is logged very two seconds.

    2018.08.17 09:36:49 ERROR [Jetty-QTP-BOSH-1112]: 
    org.jivesoftware.openfire.handler.IQvCardHandler - VCard provider is read-only.
    java.lang.UnsupportedOperationException: VCard provider is read-only.
            at org.jivesoftware.openfire.vcard.VCardManager.setVCard(VCardManager.java:158)
            at org.jivesoftware.openfire.handler.IQvCardHandler.handleIQ(IQvCardHandler.java:90)

**Comment by guusdk** [comment]
Note that VCards can contain binary information (a picture/avatar) - the data usage involved might be considerable.

**Comment by deleolajide** [comment]
change available in version 0.4.12

**Comment by deleolajide** [comment]
> I was unable to reproduce the continuous retry flood errors.

I have been able to reproduce the flood error. It happens when openfire is running on my production linux server. It does not happen on my Windows dev server. The offending code is the strophe re-connection plugin. Now I have to it

**Comment by guusdk** [comment]
cc @jcbrand

**Comment by guusdk** [comment]
So, what change applied the fix?

**Comment by deleolajide** [comment]
>So, what change applied the fix?

https://github.com/igniterealtime/Pade/commit/e36a2341fe0153ba8a6fa9430eba82583328d228
